retry mayastor disk pool creation in case of failures

diff --git a/addons/mayastor/chart/values.yaml b/addons/mayastor/chart/values.yaml
--- a/addons/mayastor/chart/values.yaml
+++ b/addons/mayastor/chart/values.yaml
@@ -131,7 +131,10 @@ mayastor:
               }
             }'
             echo 'Creating disk pool'
-            curl --cacert "$CACERT" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -XPOST -d "$BODY" "https://kubernetes.default.svc/apis/openebs.io/v1alpha1/namespaces/$NAMESPACE/diskpools?fieldManager=kubectl-create"
+            while ! curl --fail --cacert "$CACERT" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -XPOST -d "$BODY" "https://kubernetes.default.svc/apis/openebs.io/v1alpha1/namespaces/$NAMESPACE/diskpools?fieldManager=kubectl-create"; do
+              echo 'Creating disk pool failed, will retry'
+              sleep 5
+            done
         securityContext:
           runAsUser: 0
         volumeMounts:
