cert-manager: Update to v1.17.1 (#334)
Update the addon to use a Helm chart.

diff --git a/addons/cert-manager/enable b/addons/cert-manager/enable
--- a/addons/cert-manager/enable
+++ b/addons/cert-manager/enable
@@ -1,15 +1,58 @@
-#!/bin/bash
+#!/bin/bash -e
+
+. "${SNAP}/actions/common/utils.sh"
 
 DIR=`realpath $(dirname $0)`
 ENABLE="$SNAP/microk8s-enable.wrapper"
 KUBECTL="$SNAP/microk8s-kubectl.wrapper"
 
+REPO="https://charts.jetstack.io"
+VERSION="v1.17.1"
+
+function usage {
+  echo "Usage: microk8s enable cert-manager [OPTIONS]"
+  echo ""
+  echo "Enable the cert-manager addon."
+  echo ""
+  echo "   -h             Print this help message"
+  echo "   -r REPOSITORY  cert-manager Helm chart repository (default: ${REPO})"
+  echo "   -V VERSION     cert-manager Helm chart version (default: ${VERSION})"
+}
+
+while getopts ":hr:V:" arg; do
+  case "${arg}" in
+    V) VERSION="${OPTARG}" ;;
+    r) REPO="${OPTARG}" ;;
+    h)
+      usage
+      exit 0
+      ;;
+    :)
+      echo "Missing argument for option -${OPTARG}"
+      usage
+      exit 1
+      ;;
+    ?)
+      echo "Invalid option -${OPTARG}"
+      usage
+      exit 1
+      ;;
+  esac
+done
+
 echo "Enable DNS addon"
 $ENABLE dns
 
-echo "Enabling cert-manager"
+echo "Enable helm"
+$ENABLE helm3
 
-$KUBECTL apply -f $DIR/cert-manager.yaml
+HELM="$SNAP/microk8s-helm3.wrapper"
+
+echo "Enabling cert-manager"
+$HELM upgrade --install cert-manager cert-manager \
+  --repo "${REPO}" --version "${VERSION}" \
+  --set crds.enabled=true \
+  --create-namespace --namespace "cert-manager"
 
 echo "Waiting for cert-manager to be ready."
 while ! $KUBECTL apply -f $DIR/cert-tester.yaml > /dev/null 2>&1
