Make the hostpath's reclaim policy configurable (#77)
* configurable reclaim policies

Co-authored-by: Juraj Kosik <juraj.kosik@gmail.com>

diff --git a/addons/hostpath-storage/enable b/addons/hostpath-storage/enable
--- a/addons/hostpath-storage/enable
+++ b/addons/hostpath-storage/enable
@@ -6,6 +6,46 @@ source $SNAP/actions/common/utils.sh
 CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
 source $CURRENT_DIR/../common/utils.sh
 
+RECLAIM_POLICY="Delete"
+PARSED=$(getopt --options=r:h --longoptions=reclaim-policy:,help -- "$@")
+eval set -- "$PARSED"
+while true; do
+    case "$1" in
+        -r|--reclaim-policy)
+            RECLAIM_POLICY=$2
+            shift 2
+            ;;
+        -h|--help)
+            echo "Options:"
+            echo " -h, --help            Show this help"
+            echo " -r, --reclaim-policy  Set the reclaim policy. Available options are Delete (default) and Retain."
+            exit 0
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "invalid option -- $1"
+            exit 1
+    esac
+done
+
+declare -A allowed_reclaim_policies
+for policy in Delete Retain
+do
+    allowed_reclaim_policies[$policy]=1
+done
+
+if [[ ! ${allowed_reclaim_policies[$RECLAIM_POLICY]} ]]
+then
+  echo ""
+  echo "Please check submitted arguments."
+  echo "You can use '--reclaim-policy' to set the reclaim policy. Allowed values: "${!allowed_reclaim_policies[@]}". Defaults to 'Delete'."
+  echo "   microk8s enable hostpath-storage --reclaim-policy=Retain"
+  exit 1
+fi
+
 echo "Enabling default storage class."
 echo "WARNING: Hostpath storage is not suitable for production environments."
 echo ""
@@ -13,6 +53,8 @@ run_with_sudo mkdir -p ${SNAP_COMMON}/default-storage
 
 declare -A map
 map[\$SNAP_COMMON]="$SNAP_COMMON"
+map[\$RECLAIM_POLICY]="$RECLAIM_POLICY"
+
 use_addon_manifest hostpath-storage/storage apply "$(declare -p map)"
 echo "Storage will be available soon."
 
